#!/usr/bin/env python3
import sys
import os
import nltk

from helpers import get_user_timeline
from analyzer import Analyzer
from termcolor import colored

def main():
    
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
        
    screen_name = sys.argv[1]
    
    # retrieve user's first 50 tweets
    tweets = get_user_timeline(screen_name, 100)
    
    # invalid account
    if tweets is None:
        print("User's account either does not exist or is protected.\n")
        sys.exit(1)
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    """
    # calculate score of each tweet and output with color
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            color = "green"
        elif score < 0.0:
            color = "red"
        else:
            color = "yellow"
        print(colored("{} {}".format(score, tweet), color))
    """
    # compute total score and classify
    total = 0
    positive = 0
    negative = 0
    neutral = 0
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            positive += 1
        elif score < 0.0:
            negative += 1
        else:
            neutral += 1
        total += 1
    print("+: {}\n-: {}\nmeh: {}\n", positive, negative, neutral)
    positive = (positive/total) * 100
    negative = (negative/total) * 100
    neutral = (neutral/total) * 100
    print("TOTAL\n+: {}\n-: {}\nmeh: {}\n", positive, negative, neutral)
if __name__ == "__main__":
    main()
